### ISSUE TITLE
Build Requirements

### ISSUE THREAD

**Issue by mahimahi42** [zesterer/vast#1]
I found your repo from Scott Manley's video, and I'm interesting the concept! However, while there are compilation instructions, there are no dependencies. Could you add them for those who want to build the project?

**Comment by mahimahi42** [comment]
I'm currently putting together a list of build requirements for OS X 10.11 El Capitan, using Homebrew

**Comment by mahimahi42** [comment]
I've submitted a pull request with instructions for El Capitan (as that is my only easily available development machine)

**Comment by zesterer** [comment]
Sure. I know for a fact that Vast does build on OSX, so I'll just add them to the README.

**Comment by mahimahi42** [comment]
I'm familiar with Red Hat based/Debian based Linux distros as well if you would like me to try building on systems like Cent OS/Fedora/Ubuntu

**Comment by zesterer** [comment]
I'm currently doing a rewrite (the old graphics engine is not very adaptable for the things I plan). This rewrite will include a new build system (meson) that should automatically be capable of doing cross-compilations quite easily from Linux for various targets.

**Comment by zesterer** [comment]
If you could try building on them that would be great. I'm currently developing on Fedora 23. It cross-compiles for Windows and runs on WINE successfully. It also runs fine natively on Windows.

**Comment by zesterer** [comment]
Oh, and one thing. I advise you set up git to sync with your github profile. At the moment, you're committing things as an unknown user. It's quite easy. Instructions here: https://help.github.com/articles/set-up-git/

**Comment by mahimahi42** [comment]
All of that used to be setup, but the upgrade to El Capitan from Yosemite has screwed up so many things vis a vis command line work. Thank you for letting me know, so I can fix it!

**Comment by mahimahi42** [comment]
From my end all of my information is coming up both on GitHub and from a fresh pull. Could you show me where it says I'm an Unknown User?

**Comment by zesterer** [comment]
Here: https://github.com/zesterer/vast/commit/2822529467f7f145f05b0465ee0f60808fea87dd It says it cannot validate your email address.

**Comment by mahimahi42** [comment]
<img width="1280" alt="screen shot 2016-01-28 at 6 16 48 pm" src="https://cloud.githubusercontent.com/assets/468856/12662002/5cddb09a-c5eb-11e5-8fba-bdd76451a609.png">

Shows fine for me

**Comment by zesterer** [comment]
Have you told GitHub that this is a valid email address for you? Check your GitHub settings.

**Comment by mahimahi42** [comment]
Yes it is my GitHub email address

**Comment by mahimahi42** [comment]
While my profile email is that, my settings email is different. I will update it!

**Comment by mahimahi42** [comment]
I have now set my primary email address to the one in my git configuration, hopefully alleviating future merge issues

**Comment by zesterer** [comment]
Yep, GitHub now recognises you.

**Comment by zesterer** [comment]
Thanks for contributing to the project! I'm hoping this rewrite I'm currently doing will greatly increase the rate of development. This project has been going on for close to 9 months now and all I have to show for it is a fancy spinning spacecraft. Time to fix that I think.
