### ISSUE TITLE
Hey you guys got a chat channel or something? Is there a TODO?

### ISSUE THREAD

**Issue by paezao** [zesterer/vast#3]

**Comment by zesterer** [comment]
Hello! Thanks for taking an interest in the project. For now, this is a personal project of mine I've been working on. But increasingly I see people visiting the project, so I'm tempted to set up a Freenode IRC channel for it. Perhaps if we have a few people working on it, this project can really start to take flight, if you'll excuse the pun.

For now, the "##vast" channel on Freenode is where you'll find me hanging out most of the time.

**Comment by paezao** [comment]
Cool Ill meet you there.
